### ISSUE TITLE
tourism data downloaded doesn't have the columns  'Year' and 'Month'

### ISSUE THREAD

**Issue by samosun** [jlgleason/hts-constrained-embeddings#2]
Hi, Jeffrey, thanks for sharing the code and data, but I found that the tourism data I downloaded from link( https://robjhyndman.com/publications/hierarchical-tourism/) doesn't have the columns  'Year' and 'Month', could you share the raw data you preprocessed in code?

**Comment by jlgleason** [comment]
Thank you for pointing this out! I realize the data download link I've had in the readme is incorrect - I've now updated it to reflect the correct download link.
